### ISSUE TITLE
Why is the value of each dimension of the embedding that I get so large?

### ISSUE THREAD

**Issue by WangFeng666** [QuanLab/node2vec-spark#1]
Hi, I'm trying to run node2vec using the Spark implementation on a large graph (~0.6M nodes, ~20M edges. Why is the value of each dimension of the embedding that I get so large? 
<img width="679" alt="企业微信截图_20191119171612" src="https://user-images.githubusercontent.com/23021317/69133133-5a33e280-0af0-11ea-94dc-5666aab6db79.png">
so please tell me why, 
thank you !
@QuanLab

**Comment by QuanLab** [comment]
Can you provide more detail about the problem or show a part of input? it would be helpful for me to solve this issue.

**Comment by WangFeng666** [comment]
I can run, but embedding is not well. I wonder if it's because each dimension is too large.
a part of input
![1574229801(1)](https://user-images.githubusercontent.com/23021317/69213404-f61c2780-0b9e-11ea-8d2a-b46929704180.jpg)

**Comment by WangFeng666** [comment]
The first column is id of users, and the second column is index for words(-1~-7000)

**Comment by QuanLab** [comment]
Read the document again and make sure that you are fully understand node2vec algorithm and what input you need. This issue will be closed.
